USE [master]
GO

/****** Object:  Database [kirtasiyeDB]    Script Date: 8.12.2022 07:36:07 ******/
CREATE DATABASE [kirtasiyeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kirtasiyeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\kirtasiyeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'kirtasiyeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVER\MSSQL\DATA\kirtasiyeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kirtasiyeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kirtasiyeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kirtasiyeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kirtasiyeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kirtasiyeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kirtasiyeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET RECOVERY FULL 
GO

ALTER DATABASE [kirtasiyeDB] SET  MULTI_USER 
GO

ALTER DATABASE [kirtasiyeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kirtasiyeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kirtasiyeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kirtasiyeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [kirtasiyeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kirtasiyeDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [kirtasiyeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [kirtasiyeDB] SET  READ_WRITE 
GO

